server:
  host: "127.0.0.1"
  port: 8080

audit:
  enabled: true
  server: "192.168.1.100"
  port: 9000
  buffer_size: 1000

scanner:
  file:
    exclude_paths:
      - /proc
      - /sys
    fast_hash: true
    fast_hash_size: 100MB
    fast_hash_chunk: 2MB

storage:
  data_dir: "./data"
  process_system_file: "process_system.data"
  file_system_file: "file_system.data"