server:
  host: "127.0.0.1"
  port: 8080

log:
  level: "info"
  # level: "debug"

audit:
  enabled: true
  server: "192.168.1.100"
  port: 9000
  buffer_size: 1000

scanner:
  hash:
    # algorithm: "sha256"
    # algorithm: "md5"
    algorithm: "xxhash64"
  file:
    include_paths:
      - /home/wuko233/Downloads
    exclude_paths:
      - /proc
      - /sys
    fast_hash: true
    fast_hash_size: 100MB
    fast_hash_chunk: 2MB
  process:
    interval: 30 # seconds

storage:
  data_dir: "./data"
  process_system_file: "process_system.data"
  file_system_file: "file_system.data"
  dubious_file_list_file: "dubious_files.data"